global:
  scrape_interval:     15s
  evaluation_interval: 5s

rule_files:
  - 'prometheus.rules.yml'
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100', '192.168.50.6:9100', '192.168.50.7:9100']
        labels:
          group: 'production'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:9093"
